"use strict";
exports.__esModule = true;
exports.APP_ID_ONESIGNAL = exports.REST_API_KEY_ONESIGNAL = exports.TWILIO_PHONE_NUMBER = exports.TWILIO_AUTH_TOKEN = exports.TWILIO_ACCOUNT_SID = exports.ADMIN_PHONENUMBER = exports.JWT_SECRET = exports.DB_NAME = exports.DB_PASSWORD = exports.DB_USER = exports.DB_PORT = exports.DB_HOST = exports.PORT = void 0;
var dotenv_1 = require("dotenv");
(0, dotenv_1.config)();
exports.PORT = process.env.PORT || 3001;
exports.DB_HOST = process.env.DB_HOST || "147.93.3.7";
exports.DB_PORT = parseInt(process.env.DB_PORT) || 3306;
exports.DB_USER = process.env.DB_USER || "legado_user";
exports.DB_PASSWORD = process.env.DB_PASSWORD || "misiondonacion1205";
exports.DB_NAME = process.env.DB_NAME || "legado_db";
exports.JWT_SECRET = process.env.JWT_SECRET || "test";
exports.ADMIN_PHONENUMBER = process.env.ADMIN_PHONENUMBER || "+11234567890";
exports.TWILIO_ACCOUNT_SID = process.env.TWILIO_ACCOUNT_SID || "AC000000000000000000000000";
exports.TWILIO_AUTH_TOKEN = process.env.TWILIO_AUTH_TOKEN || "abc";
exports.TWILIO_PHONE_NUMBER = process.env.TWILIO_PHONE_NUMBER || "+573112223333";
// export const PUBLIC_VAPID_KEY = process.env.PUBLIC_VAPID_KEY || "testPublic";
// export const PRIVATE_VAPID_KEY = process.env.PRIVATE_VAPID_KEY || "testPrivate";
exports.REST_API_KEY_ONESIGNAL = process.env.REST_API_KEY_ONESIGNAL || "test";
exports.APP_ID_ONESIGNAL = process.env.APP_ID_ONESIGNAL || "test";
